name: dropbox_client
description: Dropbox flutter plugin
version: 0.5.0
#author: ChunKoo Park <mix1009@gmail.com>
homepage: https://github.com/mix1009/FlutterDropbox

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.mix1009.dropbox
    pluginClass: DropboxPlugin

